import os
from datetime import datetime
from typing import Any, Optional
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from sqlalchemy.orm import Session
from models.audit.audit_trail import AuditActionType
from repositories.audit_repository import AuditRepository
from repositories.recipe_repository import RecipeRepository
from repositories.batch_repository import BatchRepository
from repositories.recipe_parameter_repository import RecipeParameterRepository
from services.audit_log_service import AuditLogService

class ReportService:
    """
    Clinical service to generate mandatory PDF-only reports (Req #18, #19, #20).
    """
    def __init__(self, session: Session):
        self.session = session
        self.audit_repo = AuditRepository(session)
        self.recipe_repo = RecipeRepository(session)
        self.batch_repo = BatchRepository(session)
        self.param_repo = RecipeParameterRepository(session)
        self.reports_dir = "reports"
        if not os.path.exists(self.reports_dir):
            os.makedirs(self.reports_dir)

    def _generate_base_pdf(self, filename: str, title: str, user_name: str, elements: list, target_path: Optional[str] = None):
        """
        Internal PDF generator enforcing clinical metadata requirements (Req #20).
        """
        full_path = target_path if target_path else os.path.join(self.reports_dir, filename)
        doc = SimpleDocTemplate(full_path, pagesize=A4)
        styles = getSampleStyleSheet()
        
        # Clinical Metadata Header (Req #20)
        elements.insert(0, Paragraph(f"<b>{title}</b>", styles['Title']))
        elements.insert(1, Paragraph(f"Report Generated By: {user_name}", styles['Normal']))
        elements.insert(2, Paragraph(f"Generation Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        elements.insert(3, Spacer(1, 12))
        
        # Unmodifiable Footer (Clinical Signature Lines)
        elements.append(Spacer(1, 36))
        elements.append(Paragraph("___________________________", styles['Normal']))
        elements.append(Paragraph("System Administrator Signature", styles['Normal']))
        
        doc.build(elements)
        return full_path

    def generate_audit_report(
        self,
        request_user: str,
        start_date: datetime,
        end_date: datetime,
        user_id: Optional[int] = None,
        user_ids: Optional[list[int]] = None,
        action_type: Optional[AuditActionType] = None,
        target_path: Optional[str] = None
    ) -> str:
        """
        Generates a comprehensive Audit Trail Report for regulatory review.
        """
        import html
        filename = f"Audit_Trail_{datetime.now().strftime('%Y%H%M%S')}.pdf"
        elements = []
        styles = getSampleStyleSheet()

        # Define custom paragraph styles for cell wrapping
        cell_style = ParagraphStyle(
            'AuditCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=7,
            leading=9,
            alignment=1  # Center aligned
        )
        header_style = ParagraphStyle(
            'AuditHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=10,
            alignment=1  # Center aligned
        )

        def make_cell(text: str, is_header: bool = False):
            escaped = html.escape(str(text or ""))
            style = header_style if is_header else cell_style
            return Paragraph(escaped, style)

        # Fetch logs using the same filter semantics as the Audit Trail page.
        audit_log_service = AuditLogService(self.session)
        logs = audit_log_service.search_logs(
            user_id=user_id,
            user_ids=user_ids,
            action_type=action_type,
            start_date=start_date,
            end_date=end_date,
            limit=500
        )
        
        headers = [
            make_cell("Action / Field", is_header=True),
            make_cell("Old Value", is_header=True),
            make_cell("New Value", is_header=True),
            make_cell("User Name", is_header=True),
            make_cell("Create Date", is_header=True),
            make_cell("Action Details / Reason", is_header=True),
            make_cell("Signature Meaning", is_header=True)
        ]
        
        data = [headers]
        for log in logs:
            action_text = log.action_type.value
            old_val = "N/A"
            new_val = "N/A"
            
            # Logic to extract descriptive action and values
            if log.action_type in [AuditActionType.EDIT, AuditActionType.APPEND]:
                if isinstance(log.new_value, dict) and "parameter" in log.new_value:
                    # Clean parameter name for better display (e.g. batch_number -> Batch Number)
                    param_name = log.new_value["parameter"].replace('_', ' ').title()
                    action_text = param_name
                    new_val_raw = log.new_value.get("value", "—")
                    new_val = str(new_val_raw)
                    
                    if isinstance(log.old_value, dict):
                        old_val = str(log.old_value.get("value", "—"))
                elif log.location_screen:
                    action_text = f"{log.action_type.value} ({log.location_screen})"
            
            # AM/PM formatting as per image
            timestamp_str = log.audit_timestamp.strftime('%m/%d/%Y %H:%M %p') if log.audit_timestamp else "—"
            
            data.append([
                make_cell(action_text),
                make_cell(old_val),
                make_cell(new_val),
                make_cell(log.user.user_name if log.user else "System"),
                make_cell(timestamp_str),
                make_cell(log.reason or "—"),
                make_cell(log.signature_meaning or "—")
            ])

        # Column widths adjusted for common content sizes (Total width = 520)
        table = Table(data, hAlign='CENTER', colWidths=[90, 50, 50, 60, 85, 115, 70])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f2f2f2")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.black),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
            ('TOPPADDING', (0,0), (-1,-1), 4),
        ]))
        
        elements.append(table)
        return self._generate_base_pdf(filename, "Audit Trail Report", request_user, elements, target_path=target_path)

    def generate_recipe_report(self, request_user: str, recipe_id: int, target_path: Optional[str] = None) -> str:
        """
        Generates a detailed Batch/Setting Report showing critical parameters (Req #20).
        """
        recipe = self.recipe_repo.get_by_id(recipe_id)
        if not recipe:
            raise ValueError("Batch not found.")

        filename = f"Batch_{recipe.recipe_number}_{datetime.now().strftime('%Y%H%M%S')}.pdf"
        elements = []
        styles = getSampleStyleSheet()

        elements.append(Paragraph(f"Batch Detail: {recipe.recipe_number}", styles['Heading2']))
        elements.append(Spacer(1, 12))

        # Critical Parameters Table (Req #20)
        params = self.param_repo.get_by_recipe(recipe_id)
        data = [["Parameter Name", "Value"]]
        for p in params:
            # Extract actual value from JSONB dict
            val = p.current_value
            if isinstance(val, dict):
                val = val.get("value", val)
            
            data.append([
                p.parameter_name, 
                str(val) if val is not None else ""
            ])

        # Use full page width (A4 = 595 points, minus margins)
        page_width = A4[0] - 72  # 72 points total margin (36 each side)
        col_widths = [page_width * 0.5, page_width * 0.5]
        table = Table(data, colWidths=col_widths)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.navy),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        
        elements.append(table)
        return self._generate_base_pdf(filename, f"Setting/Batch Report: {recipe.recipe_number}", request_user, elements, target_path=target_path)

    def generate_batch_report(self, request_user: str, batch_id: Any, target_path: Optional[str] = None) -> str:
        """
        Generates a Batch Performance Report matching the required layout image.
        """
        batch = self.batch_repo.get_by_id(batch_id)
        if not batch:
            raise ValueError("Batch not found.")

        filename = f"Batch_{batch.batch_number}_{datetime.now().strftime('%Y%H%M%S')}.pdf"
        full_path = target_path if target_path else os.path.join(self.reports_dir, filename)
        
        doc = SimpleDocTemplate(full_path, pagesize=A4, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        elements = []
        styles = getSampleStyleSheet()
        
        # Title and Subtitle
        title_style = ParagraphStyle(name='CenteredTitle', parent=styles['Heading2'], alignment=1)
        sub_style = ParagraphStyle(name='CenteredSub', parent=styles['Normal'], alignment=1)
        
        gen_time = datetime.now().strftime('%m/%d/%Y %I:%M %p')
        elements.append(Paragraph("Batch Report", title_style))
        elements.append(Spacer(1, 10))
        elements.append(Paragraph(f"Generated by: {request_user} on {gen_time}", sub_style))
        elements.append(Spacer(1, 10))
        
        page_width = A4[0] - 72
        
        def create_line():
            t = Table([['']], colWidths=[page_width])
            t.setStyle(TableStyle([
                ('LINEABOVE', (0,0), (-1,-1), 0.75, colors.black),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (-1,-1), 0)
            ]))
            return t

        elements.append(create_line())
        elements.append(Spacer(1, 10))

        # Dates & Camera Box
        start_time = batch.started_at.strftime('%m/%d/%Y %I:%M %p') if batch.started_at else ""
        end_time = batch.finished_at.strftime('%m/%d/%Y %I:%M %p') if batch.finished_at else ""
        
        d1 = [
            [f"Batch Start Date: {start_time}", f"Batch End Date: {end_time}"],
            ["", "Camera ID: V2D611P-MMSCI4"]
        ]
        t1 = Table(d1, colWidths=[page_width*0.5, page_width*0.5])
        t1.setStyle(TableStyle([
            ('ALIGN', (0,0), (0,-1), 'LEFT'),
            ('ALIGN', (1,0), (1,-1), 'RIGHT'),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        elements.append(t1)
        elements.append(Spacer(1, 5))
        elements.append(create_line())
        elements.append(Spacer(1, 10))

        # Parameters Fetch
        params = self.param_repo.get_by_recipe(batch.recipe_id) if batch.recipe_id else []
        def get_p(name, d=""):
            for p in params:
                if p.parameter_name == name:
                    val = p.current_value
                    if isinstance(val, dict): return str(val.get("value", d))
                    return str(val) if val is not None else d
            return d

        med_name = get_p("medicine_name", "")
        pharma_code = get_p("batch_number", "")
        good_count_str = get_p("good_count", "0")
        bad_count_str = get_p("wrong_count", "0")
        
        try:
            good_cnt = float(good_count_str)
        except ValueError:
            good_cnt = 0.0
            
        try:
            bad_cnt = float(bad_count_str)
        except ValueError:
            bad_cnt = 0.0
            
        total_cnt = good_cnt + bad_cnt
        good_pct = (good_cnt / total_cnt * 100.0) if total_cnt > 0 else 0.0
        bad_pct = (bad_cnt / total_cnt * 100.0) if total_cnt > 0 else 0.0
        
        op_name = batch.operator.full_name if batch.operator else ""
        op_email = batch.operator.user_name if batch.operator else ""

        # Machine Details Box
        d2 = [
            ["Machine ID: 4525000", f"Product Name: {med_name}"],
            ["Machine Name: CVC 302A", f"Pharma Code: {pharma_code}"],
            ["Machine with CMS Imaging Process System", "OCR: "],
            ["Operator Name: ", ""],
            [op_name, ""],
            [op_email, ""]
        ]
        t2 = Table(d2, colWidths=[page_width*0.5, page_width*0.5])
        t2.setStyle(TableStyle([
            ('ALIGN', (0,0), (0,-1), 'LEFT'),
            ('ALIGN', (1,0), (1,-1), 'RIGHT'),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        elements.append(t2)
        elements.append(Spacer(1, 5))
        elements.append(create_line())
        elements.append(Spacer(1, 10))

        # Output Percentages Box
        d3 = [
            [f"Number of good items: {int(good_cnt)}", f"Number of bad items: {int(bad_cnt)}"],
            [f"Percent of good items: {good_pct:.2f}", f"Percent of bad items: {bad_pct:.2f}"]
        ]
        t3 = Table(d3, colWidths=[page_width*0.5, page_width*0.5])
        t3.setStyle(TableStyle([
            ('ALIGN', (0,0), (0,-1), 'LEFT'),
            ('ALIGN', (1,0), (1,-1), 'RIGHT'),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 10),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        elements.append(t3)
        
        doc.build(elements)
        return full_path
